# Generated by Django 4.1.5 on 2024-02-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class_Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=64)),
                ('class_Grade_GPA', models.FloatField()),
                ('class_Grade_Letter', models.CharField(max_length=2)),
            ],
        ),
    ]
