# Generated by Django 4.1.5 on 2024-02-09 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_grades',
            old_name='class_name',
            new_name='class_Name',
        ),
    ]
