# Generated by Django 4.1.5 on 2024-05-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0002_rename_class_name_class_grades_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignmentName', models.CharField(max_length=64)),
                ('assignmentGradeNumber', models.FloatField()),
                ('assignmentGradeLetter', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=64)),
                ('examGradeNumber', models.FloatField()),
                ('examGradeLetter', models.CharField(max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='class_grades',
            old_name='class_Grade_GPA',
            new_name='classGradeGPA',
        ),
        migrations.RenameField(
            model_name='class_grades',
            old_name='class_Grade_Letter',
            new_name='classGradeLetter',
        ),
        migrations.RenameField(
            model_name='class_grades',
            old_name='class_Name',
            new_name='className',
        ),
        migrations.AddField(
            model_name='class_grades',
            name='classGradeNumber',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
