# Generated by Django 4.1.5 on 2024-05-09 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0003_assignments_exam_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assignments',
            new_name='assignment',
        ),
        migrations.RenameModel(
            old_name='class_Grades',
            new_name='class_Grade',
        ),
    ]
