# Generated by Django 4.1.5 on 2024-05-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0004_rename_assignments_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=64)),
                ('classId', models.CharField(max_length=16)),
                ('classSection', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='class_grade',
            name='className',
        ),
    ]
