# Generated by Django 4.1.5 on 2024-05-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0007_class_attributes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_attributes',
            name='user',
        ),
    ]
