# Generated by Django 4.1.5 on 2024-05-29 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0009_class_attributes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_attributes_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Grades.class_attributes'),
            preserve_default=False,
        ),
    ]
