# Generated by Django 4.1.5 on 2024-05-30 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grades', '0010_remove_assignment_id_assignment_class_attributes_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='class_attributes_ptr',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examGradeLetter',
        ),
        migrations.AddField(
            model_name='assignment',
            name='class_attributes',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Grades.class_attributes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_grade',
            name='examGradeLetter',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
    ]
