# Generated by Django 4.1.5 on 2024-05-30 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grades', '0011_remove_assignment_class_attributes_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('course_number', models.CharField(blank=True, max_length=16, null=True)),
                ('requirement', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_gpa', models.FloatField(blank=True, null=True)),
                ('grade_letter', models.CharField(blank=True, max_length=2, null=True)),
                ('grade_number', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='class_attributes',
            name='user',
        ),
        migrations.DeleteModel(
            name='class_Grade',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='examName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assignmentGradeLetter',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assignmentGradeNumber',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assignmentName',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examGradeNumber',
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classattributes',
            name='class_grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grades.grade'),
        ),
        migrations.AddField(
            model_name='classattributes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grades.grade'),
        ),
        migrations.AddField(
            model_name='exam',
            name='class_grade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Grades.grade'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='class_attributes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grades.classattributes'),
        ),
        migrations.DeleteModel(
            name='class_attributes',
        ),
    ]
